### PR TITLE
plugin

### PR DESCRIPTION
**Pull request by l3r8yJ**
@volodya-lombrozo what do you think?

### CODE REVIEW

**Comment by l3r8yJ** [comment]
never mind, the java versions are incompatible

**Comment by volodya-lombrozo** [comment]
@l3r8yJ It would be nice to add statan plugin, actually. Are you considering to downgrade Java version to `8`?

**Comment by l3r8yJ** [comment]
@volodya-lombrozo I'm looking for a way to stay with both versions of java `8` and `17`. The first way to do it is multiple repositories, but I don't really like that, maybe you know another way to do it?

**Comment by l3r8yJ** [comment]
@volodya-lombrozo take a look, please

**Comment by l3r8yJ** [comment]
@volodya-lombrozo reminder

**Comment by l3r8yJ** [comment]
@volodya-lombrozo updated to `0.1.4` with java `8` support and couple new features

**Comment by volodya-lombrozo** [comment]
@l3r8yJ Nice improvement! Thank you. 
@rultor merge.

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Pull request merged**
