### PR TITLE
316

### LINKED ISSUE #316: Update the LICENSE
Right now we use `Volodya` in license description. It would be better to use `Volodya Lombrozo`

### PR DESCRIPTION
**Pull request by l3r8yJ**
closes #316 

---

## PR-Codex overview
This PR updates the copyright year from 2023 to 2024 in multiple files.

### Detailed summary
- Updated the copyright year from 2023 to 2024 in `LICENSE.txt`
- Updated the copyright year from 2023 to 2024 in `pom.xml`
- Updated the copyright year from 2023 to 2024 in `src/it/settings.xml`
- Updated the copyright year from 2023 to 2024 in `src/it/assertions/pom.xml`
- Updated the copyright year from 2023 to 2024 in `src/it/exclusions/pom.xml`
- Updated the copyright year from 2023 to 2024 in `src/it/all-incorrect/pom.xml`
- Updated the copyright year from 2023 to 2024 in `src/it/empty-project/pom.xml`
- Updated the copyright year from 2023 to 2024 in `src/it/correct-test-names/pom.xml`
- Updated the copyright year from 2023 to 2024 in `src/it/all-have-production-class/pom.xml`
- Updated the copyright year from 2023 to 2024 in `src/it/assertions/verify.groovy`
- Updated the copyright year from 2023 to 2024 in `src/it/exclusions/verify.groovy`
- Updated the copyright year from 2023 to 2024 in `src/it/all-incorrect/verify.groovy`
- Updated the copyright year from 2023 to 2024 in `src/it/empty-project/verify.groovy`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/Java17Test.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/TestSimple.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/EnumInTests.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/package-info.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/TestWrongName.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/JUnitCondition.java`
- Updated the copyright year from 2023 to 2024 in `src/it/correct-test-names/verify.groovy`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/IntegrationTest.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/TestWithoutTests.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/TestParameterized.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/TestWithAssertions.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/TestWithSuppressed.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/SuppressedInterface.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/SuppressedAnnotation.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/AnnotationDeclaration.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/JUnitAfterAllCallback.java`
- Updated the copyright year from 2023 to 2024 in `src/test/resources/JunitAssertTrueHitter.java`
- Updated the copyright year from 2023 to 2024 in `src/it/all-have-production-class/verify.groovy`
- Updated the copyright year from

> The following files were skipped due to too many changes: `src/main/java/com/github/lombrozo/testnames/Rule.java`, `src/it/all-incorrect/src/test/java/LineHitterTest.java`, `src/main/java/com/github/lombrozo/testnames/Project.java`, `src/main/java/com/github/lombrozo/testnames/Suspect.java`, `src/test/java/com/github/lombrozo/testnames/CopTest.java`, `src/it/all-incorrect/src/test/java/ForbiddenWordTest.java`, `src/main/java/com/github/lombrozo/testnames/RuleName.java`, `src/main/java/com/github/lombrozo/testnames/TestCase.java`, `src/it/correct-test-names/src/test/java/CorrectNameIT.java`, `src/it/correct-test-names/src/test/java/ITCorrectName.java`, `src/it/correct-test-names/src/test/java/IncorrectName.java`, `src/main/java/com/github/lombrozo/testnames/Assertion.java`, `src/main/java/com/github/lombrozo/testnames/Complaint.java`, `src/main/java/com/github/lombrozo/testnames/TestClass.java`, `src/it/all-incorrect/src/test/java/UsesInheritenceTest.java`, `src/it/correct-test-names/src/test/java/CorrectNameTest.java`, `src/it/correct-test-names/src/test/java/IncorrectITName.java`, `src/it/correct-test-names/src/test/java/TestCorrectName.java`, `src/test/java/com/github/lombrozo/testnames/ProjectTest.java`, `src/it/correct-test-names/src/test/java/CorrectNameTests.java`, `src/it/correct-test-names/src/test/java/TestsCorrectName.java`, `src/main/java/com/github/lombrozo/testnames/ValidateMojo.java`, `src/main/java/com/github/lombrozo/testnames/package-info.java`, `src/main/java/com/github/lombrozo/testnames/rules/ml/Tag.java`, `src/test/java/com/github/lombrozo/testnames/package-info.java`, `src/it/correct-test-names/src/test/java/CorrectNameITCase.java`, `src/it/correct-test-names/src/test/java/ITCaseCorrectName.java`, `src/it/correct-test-names/src/test/java/IncorrectTestName.java`, `src/it/all-have-production-class/src/test/java/CorrectTest.java`, `src/it/all-have-production-class/src/test/java/MyInterface.java`, `src/it/correct-test-names/src/test/java/IncorrectTestsName.java`, `src/main/java/com/github/lombrozo/testnames/JUnitExtension.java`, `src/test/java/com/github/lombrozo/testnames/rules/RuleTest.java`, `src/it/all-have-production-class/src/test/java/MyAnnotation.java`, `src/it/all-have-production-class/src/test/java/RuleNameTest.java`, `src/it/all-have-production-class/src/test/java/package-info.java`, `src/it/correct-test-names/src/test/java/CorrectNameTestCase.java`, `src/it/correct-test-names/src/test/java/IncorrectITCaseName.java`, `src/it/correct-test-names/src/test/java/TestCaseCorrectName.java`, `src/main/java/com/github/lombrozo/testnames/ProductionClass.java`, `src/it/all-have-production-class/src/main/java/ComplaintClass.java`, `src/it/all-have-production-class/src/test/java/JUnitCondition.java`, `src/it/all-have-production-class/src/test/java/SuppressedTest.java`, `src/it/correct-test-names/src/test/java/IncorrectTestCaseName.java`, `src/it/exclusions/src/test/java/TestDoesntHaveProductionClass.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/ByName.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleNotSpam.java`, `src/main/java/com/github/lombrozo/testnames/rules/package-info.java`, `src/test/java/com/github/lombrozo/testnames/rules/package-info.java`, `src/it/all-have-production-class/src/test/java/it/CorrectITCase.java`, `src/it/all-have-production-class/src/test/java/JavaGeneratedTest.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/TestsOnly.java`, `src/main/java/com/github/lombrozo/testnames/rules/LineHitterRule.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleSuppressed.java`, `src/main/java/com/github/lombrozo/testnames/rules/ml/ModelSource.java`, `src/main/java/com/github/lombrozo/testnames/bytecode/package-info.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleConditional.java`, `src/main/java/com/github/lombrozo/testnames/rules/ml/package-info.java`, `src/test/java/com/github/lombrozo/testnames/bytecode/package-info.java`, `src/test/java/com/github/lombrozo/testnames/rules/ml/package-info.java`, `src/it/all-have-production-class/src/test/java/SuppressedInterface.java`, `src/main/java/com/github/lombrozo/testnames/bytecode/BytecodeClass.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleNotCamelCase.java`, `src/main/java/com/github/lombrozo/testnames/rules/RulePresentTense.java`, `src/it/all-have-production-class/src/test/java/SuppressedAnnotation.java`, `src/main/java/com/github/lombrozo/testnames/complaints/package-info.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/package-info.java`, `src/test/java/com/github/lombrozo/testnames/complaints/package-info.java`, `src/test/java/com/github/lombrozo/testnames/javaparser/package-info.java`, `src/it/all-have-production-class/src/test/java/JUnitAfterAllCallback.java`, `src/main/java/com/github/lombrozo/testnames/TestClassCharacteristics.java`, `src/main/java/com/github/lombrozo/testnames/bytecode/BytecodeProject.java`, `src/test/java/com/github/lombrozo/testnames/rules/LineHitterRuleTest.java`, `src/it/all-have-production-class/src/test/java/JUnitAfterEachCallback.java`, `src/it/all-have-production-class/src/test/java/JUnitBeforeAllCallback.java`, `src/it/all-have-production-class/src/test/java/JUnitParameterResolver.java`, `src/main/java/com/github/lombrozo/testnames/complaints/ComplaintClass.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/UnknownMessage.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleCorrectTestCase.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleCorrectTestName.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleOnlyTestMethods.java`, `src/it/all-have-production-class/src/test/java/JUnitBeforeEachCallback.java`, `src/main/java/com/github/lombrozo/testnames/bytecode/BytecodeTestClass.java`, `src/main/java/com/github/lombrozo/testnames/complaints/ComplaintLinked.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserClass.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/ParsedAssertion.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/StingExpression.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleAssertionMessage.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleCorrectTestCases.java`, `src/test/java/com/github/lombrozo/testnames/javaparser/JavaTestClasses.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/AssertionOfJUnit.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserMethod.java`, `src/main/java/com/github/lombrozo/testnames/complaints/ComplaintCompound.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserProject.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleInheritanceInTests.java`, `src/main/java/com/github/lombrozo/testnames/rules/ml/ModelSourceInternet.java`, `src/main/java/com/github/lombrozo/testnames/rules/ml/RulePresentSimpleMl.java`, `src/test/java/com/github/lombrozo/testnames/bytecode/BytecodeProjectTest.java`, `src/main/java/com/github/lombrozo/testnames/ProjectWithoutJUnitExtensions.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserTestCase.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleNotContainsTestWord.java`, `src/test/java/com/github/lombrozo/testnames/complaints/ComplaintClassTest.java`, `src/test/java/com/github/lombrozo/testnames/rules/RuleCorrectTestNameTest.java`, `src/test/java/com/github/lombrozo/testnames/rules/RuleOnlyTestMethodsTest.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/AssertionOfHamcrest.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserAssertion.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserTestClass.java`, `src/main/java/com/github/lombrozo/testnames/rules/ml/ModelSourceFileSystem.java`, `src/test/java/com/github/lombrozo/testnames/bytecode/BytecodeTestClassTest.java`, `src/test/java/com/github/lombrozo/testnames/rules/RuleAssertionMessageTest.java`, `src/test/java/com/github/lombrozo/testnames/rules/RuleCorrectTestCasesTest.java`, `src/test/java/com/github/lombrozo/testnames/javaparser/AssertionOfJUnitTest.java`, `src/main/java/com/github/lombrozo/testnames/bytecode/BytecodeProductionClass.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/SuppressedAnnotations.java`, `src/test/java/com/github/lombrozo/testnames/javaparser/JavaParserProjectTest.java`, `src/test/java/com/github/lombrozo/testnames/rules/RuleInheritanceInTestsTest.java`, `src/test/java/com/github/lombrozo/testnames/rules/ml/RulePresentSimpleMlTest.java`, `src/it/all-have-production-class/src/test/java/EOorg/EOeolang/EOboolEOnotTest.java`, `src/main/java/com/github/lombrozo/testnames/complaints/ComplaintWrongTestName.java`, `src/test/java/com/github/lombrozo/testnames/ProjectWithoutJUnitExtensionsTest.java`, `src/test/java/com/github/lombrozo/testnames/javaparser/JavaParserTestCaseTest.java`, `src/test/java/com/github/lombrozo/testnames/rules/RuleNotContainsTestWordTest.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleNotUsesSpecialCharacters.java`, `src/test/java/com/github/lombrozo/testnames/javaparser/AssertionOfHamcrestTest.java`, `src/test/java/com/github/lombrozo/testnames/javaparser/JavaParserAssertionTest.java`, `src/test/java/com/github/lombrozo/testnames/javaparser/JavaParserTestClassTest.java`, `src/test/java/com/github/lombrozo/testnames/rules/ml/ModelSourceFileSystemTest.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserCharacteristics.java`, `src/main/java/com/github/lombrozo/testnames/javaparser/JavaParserProductionClass.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleAllTestsHaveProductionClass.java`, `src/test/java/com/github/lombrozo/testnames/complaints/ComplaintWrongTestNameTest.java`, `src/test/java/com/github/lombrozo/testnames/javaparser/JavaParserCharacteristicsTest.java`, `src/test/java/com/github/lombrozo/testnames/javaparser/JavaParserProductionClassTest.java`, `src/main/java/com/github/lombrozo/testnames/bytecode/BytecodeTestClassCharacteristics.java`, `src/test/java/com/github/lombrozo/testnames/rules/RuleAllTestsHaveProductionClassTest.java`, `src/test/java/com/github/lombrozo/testnames/bytecode/BytecodeTestClassCharacteristicsTest.java`, `src/it/empty-project/target/generated-test-sources/com/github/lombrozo/testnames/CorrectNameIT.java`, `src/it/all-have-production-class/target/generated-sources/com/github/lombrozo/testnames/JavaGenerated.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by l3r8yJ** [comment]
@volodya-lombrozo take a look, please

**Comment by volodya-lombrozo** [comment]
@l3r8yJ, it looks good to me. Thank you very much!

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@l3r8yJ Btw, I highly recommend to use [commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification).

**Pull request merged**
